name: "anosppnn"
description: "ANOSPP data nearest neighbour mosquito species ID"
keywords:
  - amplicon
tools:
  - "anosppnn":
      description: "ANOSPP data nearest neighbour mosquito species ID"
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: "['MIT']"

input:
  # Only when we have meta
  # - meta:
  #     type: map
  #     description: |
  #       Groovy Map containing sample information
  #       e.g. [ id:'test', single_end:false ]

  - haps:
      type: file
      description: haplotypes tsv file produced by anospp-prep
      pattern: "*.tsv"

  - comb_stats:
      type: file
      description: combined stats tsv file produced by anospp-prep
      pattern: "*.tsv"

  - ref_dir:
      type: file
      description: path to directory with ANOSPP reference data

  - nn_ref_version:
      type: string
      description: NN reference directory name within ref_dir
      pattern: 'nnv*'  

  - plasm_ref_version:
      type: string
      description: Plasmodium reference directory name within ref_dir
      pattern: 'plasmv*'

  - plasm_assignment:
      type: file
      description: Plasmodium assignment tsv produced with anospp-plasm
      pattern: '*.tsv'

  - nn_assignment_threshold:
      type: number
      description: NN required assignment fraction for species naming

output:
  #Only when we have meta
  # - meta:
  #     type: map
  #     description: |
  #       Groovy Map containing sample information
  #       e.g. [ id:'test', single_end:false ]

  - versions:
      type: file
      description: file containing software versions
      pattern: "versions.yml"

  - nn_haps:
      type: file
      description: NN annotated filtered haplotypes tsv
      pattern: "*.tsv"

  - nn_assignment:
      type: file
      description: NN assignment tsv
      pattern: "*.tsv"
  
  - nn_summary:
      type: file
      description: NN summary stats
      pattern: "*.txt"

  - nn_plots:
      type: file
      description: NN assignment plots
      pattern: "*.png"

authors:
  - "@amakunin"
